version: '3.8'

networks:
  calc-nest_calc_network:
    external: true

services:
  calcs_testing_system:
    container_name: calcs_testing_system
    build: 
      context: .
    env_file:
      - .env.development
    environment:
      - DB_HOST=calcs_testing_system_mysql
    volumes:
      - .:/calcs-testing-system
      - /calcs-testing-system/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run start:dev
    depends_on:
      - calcs_testing_system_mysql
    networks:
      - calc-nest_calc_network
    
  calcs_testing_system_mysql:
    container_name: calcs_testing_system_mysql
    build: ./mysql
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./mysql/db_data:/var/lib/mysql
    restart: always
    ports:
      - ${DB_PORT}:3306
    networks:
      - calc-nest_calc_network

volumes:
  mysql: