version: '3.8'

services:
  main:
    container_name: main
    build: 
      context: .
    env_file:
      - .env.development
    volumes:
      - .:/calcs-testing-system
      - /calcs-testing-system/node_modules
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - mysql
    
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - mysqldata:/var/lib/mysql/
    ports:
      - ${DB_PORT}:3306

volumes:
  mysqldata: