version: '3.8'

networks:
  default:

services:
  main:
    container_name: main
    build: 
      context: .
    env_file:
      - .env.development
    volumes:
      - .:/calcs-testing-system
      - /calcs-testing-system/node_modules
    ports:
      - ${APP_LOCAL_PORT}:${APP_DOCKER_PORT}
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - mysql
    networks:
      - default
    
  mysql:
    container_name: mysql
    build: ./mysql
    volumes:
      - ./mysql/db_data:/var/lib/mysql
    restart: always
    ports:
      - ${DB_LOCAL_PORT}:${DB_DOCKER_PORT}
    networks:
      - default

volumes:
  mysql: